### ISSUE TITLE
Could anyone please explain how to run this code in detail?

### ISSUE THREAD

**Issue by chenghz** [KPeng9510/MASS#2]
If I'm not mistaken, this code is not so well organized and can not run properly with simple modifications due to various problems I encountered. These followings are my findings:
1. Many codes are commented out but I find them actually useful. Some codes are even truncated by '$'.
2. Many paths and values are hard coded and difficult to identify and edit in a whole.
3. The branches are mixed up. For instance, codes for preprocessing nuscenes data are in master branch.

I would very appreciate it if someone can help me out.

**Comment by KPeng9510** [comment]
Hi Hongzhi,

Thanks for your findings! Currently I just uploaded a draft version and
these issues will be modified at the end of this month.

Best,
Kunyu

Cheng Hongzhi ***@***.***> 于2021年11月9日周二 下午12:54写道：

**Comment by KPeng9510** [comment]
Hi, sorry could you please by any chance tell me where is truncated by '$' ? Currently I'm modifying codes and may overlook it :)

**Comment by chenghz** [comment]
> Hi, sorry could you please by any chance tell me where is truncated by '$' ? Currently I'm modifying codes and may overlook it :)

As far as I remember, those are mainly in `label_processing_tools/ego.py` around line 159, and `label_processing_tools/lidar_seg_label_cating.py`, line 21.
Hoping that those commented codes but still useful can be uncommented and explained as well. That would be a great help to us!

**Comment by KPeng9510** [comment]
OK great, thanks! I will have a look

**Comment by KPeng9510** [comment]
Hi, I have modified some and executed again in my local, it can work now. (related tutorials are added into the readme inside folder tools_for_nuscenes)
